version: '3.9'

services:
  catalogdemo.api:
    image: ${DOCKER_REGISTRY-}catalogdemoapi
    build:
      context: .
      dockerfile: EshopDemoApi1/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
