version: '3.9'

services:
  catalogdemo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y    
    ports:
      - "5433:1433"
    volumes:
      - eshop-sqldata:/var/opt/mssql

volumes:
  eshop-sqldata:
    external: false